'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class settings

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''placeholder_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents placeholder_admin As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblacc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblacc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblnamaakun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnamaakun As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PlaceHolderchangepass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderchangepass As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lnkpassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkpassword As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLogout As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''PlaceHolderAkunBTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderAkunBTN As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''btnAkun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAkun As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''PlaceHolderAkunBackBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderAkunBackBtn As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''btnAkunKembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAkunKembali As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''plhList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plhList As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''rptData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptData As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblPaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaging As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrevious As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''plhRinci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plhRinci As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblNomor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PlaceHolderTitleEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderTitleEdit As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''PlaceHolderprofile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderprofile As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''txtIdUserRinci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdUserRinci As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUsernameRinci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUsernameRinci As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtnama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnama As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PH_Access control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PH_Access As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''DropDownAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownAccess As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PH_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PH_password As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''pw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pw As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pw2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pw2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBatal As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSimpan As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
