'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class stock

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''placeholder_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents placeholder_admin As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblacc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblacc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblnamaakun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnamaakun As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PlaceHolderchangepass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderchangepass As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lnkpassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkpassword As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLogout As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''PlaceHolderCariBTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderCariBTN As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''btnCari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCari As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''PlaceHolderCariBackBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderCariBackBtn As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''btnKembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKembali As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''plhList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plhList As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''PlaceHolderCari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderCari As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''txtCariID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCariID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCariGo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCariGo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLaporanMasuk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLaporanMasuk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLaporanKeluar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLaporanKeluar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRusak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRusak As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExpired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExpired As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrder As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptData As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblPaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaging As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrevious As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PlaceHolderTambahAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderTambahAccess As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''btnTambah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTambah As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''plhRinci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plhRinci As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblNomor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PlaceHolderTitleBaru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderTitleBaru As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''PlaceHolderTitleEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderTitleEdit As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblIdStok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdStok As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIdStokRinci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdStokRinci As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNamaLengkap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNamaLengkap As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDDataBarang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDDataBarang As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropDownJenis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownJenis As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EnableDiskon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnableDiskon As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''paneldiskon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paneldiskon As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtDiskon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiskon As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKet As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBatal As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSimpan As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''PlaceHolderDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderDetails As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''PlaceHolderDetailTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderDetailTitle As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblIdLaporanDetailjudul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdLaporanDetailjudul As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIdDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNamaUserDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNamaUserDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNamaBarangDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNamaBarangDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtJenisDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJenisDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiskonDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiskonDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUnitD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKetDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKetDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnDetailKembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDetailKembali As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
